/**
 * \file error_codes.h
 *
 * Error codes for vccrypt.
 *
 * \copyright 2018 Velo Payments, Inc.  All rights reserved.
 */

#ifndef VCCRYPT_ERROR_CODES_HEADER_GUARD
#define VCCRYPT_ERROR_CODES_HEADER_GUARD

/* make this header C++ friendly. */
#ifdef __cplusplus
extern "C" {
#endif  //__cplusplus

/**
 * \defgroup error codes for the Velo Crypto Library.
 *
 * @
 */
#define VCCRYPT_STATUS_SUCCESS 0x0000
#define VCCRYPT_ERROR_STREAM_OPTIONS_INIT_MISSING_IMPL 0x2100
#define VCCRYPT_ERROR_STREAM_INIT_INVALID_ARG 0x2105
#define VCCRYPT_ERROR_STREAM_INIT_OUT_OF_MEMORY 0x2106
#define VCCRYPT_ERROR_STREAM_INIT_BAD_ENCRYPTION_KEY 0x2107
#define VCCRYPT_ERROR_STREAM_START_ENCRYPTION_INVALID_ARG 0x210B
#define VCCRYPT_ERROR_PRNG_OPTIONS_INIT_MISSING_IMPL 0x210F
#define VCCRYPT_ERROR_PRNG_INIT_OUT_OF_MEMORY 0x2113
#define VCCRYPT_ERROR_PRNG_INIT_DEVICE_OPEN_FAILURE 0x2114
#define VCCRYPT_ERROR_PRNG_READ_FAILURE 0x2118
#define VCCRYPT_ERROR_PRNG_READ_WOULD_OVERWRITE 0x2119
#define VCCRYPT_ERROR_SUITE_OPTIONS_INIT_MISSING_IMPL 0x211D
#define VCCRYPT_ERROR_DIGITAL_SIGNATURE_INIT_INVALID_ARG 0x2121
#define VCCRYPT_ERROR_DIGITAL_SIGNATURE_OPTIONS_INIT_MISSING_IMPL 0x2125
#define VCCRYPT_ERROR_KEY_AGREEMENT_SHORT_TERM_CREATE_INVALID_ARG 0x2129
#define VCCRYPT_ERROR_KEY_AGREEMENT_OPTIONS_INIT_MISSING_IMPL 0x212D
#define VCCRYPT_ERROR_KEY_AGREEMENT_INIT_INVALID_ARG 0x2131
#define VCCRYPT_ERROR_HASH_OPTIONS_INIT_MISSING_IMPL 0x2135
#define VCCRYPT_ERROR_HASH_INIT_INVALID_ARG 0x2139
#define VCCRYPT_ERROR_HASH_INIT_OUT_OF_MEMORY 0x213A
#define VCCRYPT_ERROR_HASH_DIGEST_INVALID_ARG 0x213D
#define VCCRYPT_ERROR_HASH_FINALIZE_INVALID_ARG 0x2141
#define VCCRYPT_ERROR_BLOCK_OPTIONS_INIT_MISSING_IMPL 0x2145
#define VCCRYPT_ERROR_BLOCK_INIT_INVALID_ARG 0x2149
#define VCCRYPT_ERROR_BLOCK_INIT_BAD_ALLOCATOR 0x214A
#define VCCRYPT_ERROR_BLOCK_INIT_BAD_ENCRYPTION_KEY 0x214B
#define VCCRYPT_ERROR_BLOCK_INIT_BAD_DECRYPTION_KEY 0x214C
#define VCCRYPT_ERROR_BUFFER_INIT_OUT_OF_MEMORY 0x2150
#define VCCRYPT_ERROR_BUFFER_READ_WOULD_OVERWRITE 0x2154
#define VCCRYPT_ERROR_BUFFER_WRITE_WOULD_OVERWRITE 0x2158
#define VCCRYPT_ERROR_BUFFER_COPY_MISMATCHED_BUFFER_SIZES 0x215C
#define VCCRYPT_ERROR_MAC_OPTIONS_INIT_MISSING_IMPL 0x2160
#define VCCRYPT_ERROR_MAC_INIT_OUT_OF_MEMORY 0x2164
#define VCCRYPT_ERROR_MAC_INIT_INVALID_ARG 0x2165
#define VCCRYPT_ERROR_MAC_INIT_INVALID_KEY_MAC 0x2166
#define VCCRYPT_ERROR_MAC_DIGEST_INVALID_ARG 0x2168
#define VCCRYPT_ERROR_MAC_FINALIZE_INVALID_ARG 0x216C
/**
 * @}
 */

/* make this header C++ friendly. */
#ifdef __cplusplus
}
#endif  //__cplusplus

#endif  //VCCRYPT_ERROR_CODES_HEADER_GUARD
